# Good practice: Use official base images
#
FROM python:3.10-slim

# Good practice: upgrade distro packages (with last security patches).
#
RUN apt-get update && apt-get -y upgrade \
    && pip install --upgrade pip \
    && pip --version

RUN apt-get update && apt-get install -y procps \
    && rm -rf /var/lib/apt/lists/*

# Install mlflow dependencies:
#
WORKDIR /mlflow/

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt \
    && rm requirements.txt

# Expose mlflow ports
#
EXPOSE 5000

# Launch the mlflow server
#
CMD mlflow server --backend-store-uri ${BACKEND_STORE_URI} --default-artifact-root ${DEFAULT_ARTIFACT_ROOT} --artifacts-destination ${DEFAULT_ARTIFACTS_DESTINATION} --no-serve-artifacts --host 0.0.0.0 --port 5000


# ======================================================================================================================================
# VERBOSE Image build:
# ======================================================================================================================================

# Build the image with:

# $ docker build -f Dockerfile-as-root --progress plain --no-cache -t mlflow_tracker_slim_as_root .

# Logged info:

# #1 [internal] load build definition from Dockerfile-as-root
# #1 sha256:ff8a0ea83bb0dc6acc0fdcaed2300a88de36aa97c6854912925b9710bd076277
# #1 transferring dockerfile: 47B done
# #1 DONE 0.0s
#
# #2 [internal] load .dockerignore
# #2 sha256:10fc019044711241a7274826d275f3629a357f9fd5ae598713619ad44452ce32
# #2 transferring context: 35B done
# #2 DONE 0.0s
#
# #3 [internal] load metadata for docker.io/library/python:3.10-slim
# #3 sha256:b8cce7183299ea8471dad4044ce489ad9730ef208466a01382bd3a85a0492215
# #3 DONE 0.5s
#
# #10 [1/6] FROM docker.io/library/python:3.10-slim@sha256:7b0a5cefbcdd085faa21533c21549e55a7e66f5aed40f8d1f4de13a017e352cd
# #10 sha256:3cf59a99c4595deb0a6ac22ffe47f994a753ae4eb206482ee918e1e89f008545
# #10 CACHED
#
# #7 [internal] load build context
# #7 sha256:66a6764a42af87d187605acf688f73336c114c35a57702afedd76a07d4446042
# #7 transferring context: 37B done
# #7 DONE 0.0s
#
# #4 [2/6] RUN apt-get update && apt-get -y upgrade     && pip install --upgrade pip     && pip --version
# #4 sha256:ee326e143ec81e4f7025634419c33dcc99cdf12628189df109674795020eb0d7
# #4 0.392 Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
# #4 0.427 Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
# #4 0.451 Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
# #4 0.495 Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8183 kB]
# #4 1.227 Get:5 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [236 kB]
# #4 1.247 Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [14.6 kB]
# #4 1.975 Fetched 8642 kB in 2s (5370 kB/s)
# #4 1.975 Reading package lists...
# #4 2.283 Reading package lists...
# #4 2.579 Building dependency tree...
# #4 2.658 Reading state information...
# #4 2.670 Calculating upgrade...
# #4 2.759 The following packages will be upgraded:
# #4 2.759   tzdata
# #4 2.793 1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
# #4 2.793 Need to get 286 kB of archives.
# #4 2.793 After this operation, 20.5 kB of additional disk space will be used.
# #4 2.793 Get:1 http://deb.debian.org/debian bullseye-updates/main amd64 tzdata all 2021a-1+deb11u9 [286 kB]
# #4 2.916 debconf: delaying package configuration, since apt-utils is not installed
# #4 2.941 Fetched 286 kB in 0s (3743 kB/s)
# (Reading database ... 7031 files and directories currently installed.)
# #4 2.999 Preparing to unpack .../tzdata_2021a-1+deb11u9_all.deb ...
# #4 3.029 Unpacking tzdata (2021a-1+deb11u9) over (2021a-1+deb11u8) ...
# #4 9.090 Setting up tzdata (2021a-1+deb11u9) ...
# #4 9.152 debconf: unable to initialize frontend: Dialog
# #4 9.152 debconf: (TERM is not set, so the dialog frontend is not usable.)
# #4 9.152 debconf: falling back to frontend: Readline
# #4 9.152 debconf: unable to initialize frontend: Readline
# #4 9.152 debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.32.1 /usr/local/share/perl/5.32.1 /usr/lib/x86_64-linux-gnu/perl5/5.32 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.32 /usr/share/perl/5.32 /usr/local/lib/site_perl) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
# #4 9.152 debconf: falling back to frontend: Teletype
# #4 9.180
# #4 9.180 Current default time zone: 'Etc/UTC'
# #4 9.182 Local time is now:      Sat Apr  1 09:36:48 UTC 2023.
# #4 9.182 Universal Time is now:  Sat Apr  1 09:36:48 UTC 2023.
# #4 9.182 Run 'dpkg-reconfigure tzdata' if you wish to change it.
# #4 9.182
# #4 10.30 Requirement already satisfied: pip in /usr/local/lib/python3.10/site-packages (22.3.1)
# #4 10.45 Collecting pip
# #4 10.51   Downloading pip-23.0.1-py3-none-any.whl (2.1 MB)
# #4 10.75      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 8.6 MB/s eta 0:00:00
# #4 10.79 Installing collected packages: pip
# #4 10.79   Attempting uninstall: pip
# #4 10.79     Found existing installation: pip 22.3.1
# #4 10.85     Uninstalling pip-22.3.1:
# #4 11.02       Successfully uninstalled pip-22.3.1
# #4 11.78 Successfully installed pip-23.0.1
# #4 11.78 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
# #4 12.16 pip 23.0.1 from /usr/local/lib/python3.10/site-packages/pip (python 3.10)
# #4 DONE 13.0s
#
# #5 [3/6] RUN apt-get update && apt-get install -y procps     && rm -rf /var/lib/apt/lists/*
# #5 sha256:f85b9777f5c79b62f73815a47d1ffc804a11dbcae588afc83ba4c32618e71526
# #5 0.536 Hit:1 http://deb.debian.org/debian bullseye InRelease
# #5 0.536 Hit:2 http://deb.debian.org/debian-security bullseye-security InRelease
# #5 0.538 Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
# #5 0.716 Reading package lists...
# #5 1.020 Reading package lists...
# #5 1.314 Building dependency tree...
# #5 1.393 Reading state information...
# #5 1.470 The following additional packages will be installed:
# #5 1.470   libgpm2 libncurses6 libprocps8 psmisc
# #5 1.471 Suggested packages:
# #5 1.471   gpm
# #5 1.505 The following NEW packages will be installed:
# #5 1.505   libgpm2 libncurses6 libprocps8 procps psmisc
# #5 1.531 0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
# #5 1.531 Need to get 902 kB of archives.
# #5 1.531 After this operation, 3044 kB of additional disk space will be used.
# #5 1.531 Get:1 http://deb.debian.org/debian bullseye/main amd64 libncurses6 amd64 6.2+20201114-2 [102 kB]
# #5 1.566 Get:2 http://deb.debian.org/debian bullseye/main amd64 libprocps8 amd64 2:3.3.17-5 [63.9 kB]
# #5 1.573 Get:3 http://deb.debian.org/debian bullseye/main amd64 procps amd64 2:3.3.17-5 [502 kB]
# #5 1.617 Get:4 http://deb.debian.org/debian bullseye/main amd64 libgpm2 amd64 1.20.7-8 [35.6 kB]
# #5 1.620 Get:5 http://deb.debian.org/debian bullseye/main amd64 psmisc amd64 23.4-2 [198 kB]
# #5 1.744 debconf: delaying package configuration, since apt-utils is not installed
# #5 1.806 Fetched 902 kB in 0s (7023 kB/s)
# #5 1.875 Selecting previously unselected package libncurses6:amd64.
# (Reading database ... 7034 files and directories currently installed.)
# #5 1.879 Preparing to unpack .../libncurses6_6.2+20201114-2_amd64.deb ...
# #5 1.908 Unpacking libncurses6:amd64 (6.2+20201114-2) ...
# #5 2.058 Selecting previously unselected package libprocps8:amd64.
# #5 2.059 Preparing to unpack .../libprocps8_2%3a3.3.17-5_amd64.deb ...
# #5 2.076 Unpacking libprocps8:amd64 (2:3.3.17-5) ...
# #5 2.278 Selecting previously unselected package procps.
# #5 2.278 Preparing to unpack .../procps_2%3a3.3.17-5_amd64.deb ...
# #5 2.313 Unpacking procps (2:3.3.17-5) ...
# #5 2.520 Selecting previously unselected package libgpm2:amd64.
# #5 2.521 Preparing to unpack .../libgpm2_1.20.7-8_amd64.deb ...
# #5 2.536 Unpacking libgpm2:amd64 (1.20.7-8) ...
# #5 2.688 Selecting previously unselected package psmisc.
# #5 2.689 Preparing to unpack .../psmisc_23.4-2_amd64.deb ...
# #5 2.705 Unpacking psmisc (23.4-2) ...
# #5 2.820 Setting up libgpm2:amd64 (1.20.7-8) ...
# #5 2.863 Setting up psmisc (23.4-2) ...
# #5 2.912 Setting up libncurses6:amd64 (6.2+20201114-2) ...
# #5 2.966 Setting up libprocps8:amd64 (2:3.3.17-5) ...
# #5 3.016 Setting up procps (2:3.3.17-5) ...
# #5 3.119 Processing triggers for libc-bin (2.31-13+deb11u5) ...
# #5 DONE 3.3s
#
# #6 [4/6] WORKDIR /mlflow/
# #6 sha256:05c8ad7b6a5fe5f7a6962058db5d3acca765b9e414b9bf4c15ad15e655027dda
# #6 DONE 0.2s
#
# #8 [5/6] COPY requirements.txt .
# #8 sha256:da5a00bad78e94df040c749e06d1ff0691ac891f1348c529840a3e0cf8eedc4c
# #8 DONE 0.2s
#
# #9 [6/6] RUN pip install --no-cache-dir -r requirements.txt     && rm requirements.txt
# #9 sha256:640a4fbc115ffdd500df897b890abdfa482fd64a3aaa869971fe2fee5dc6c07e
# #9 0.950 Collecting mlflow==2.2.1
# #9 1.011   Downloading mlflow-2.2.1-py3-none-any.whl (17.6 MB)
# #9 2.404      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.6/17.6 MB 13.0 MB/s eta 0:00:00
# #9 2.449 Collecting pymysql
# #9 2.458   Downloading PyMySQL-1.0.3-py3-none-any.whl (43 kB)
# #9 2.464      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 16.0 MB/s eta 0:00:00
# #9 2.547 Collecting pyyaml<7,>=5.1
# #9 2.564   Downloading PyYAML-6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (682 kB)
# #9 2.619      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 682.2/682.2 kB 13.2 MB/s eta 0:00:00
# #9 2.734 Collecting databricks-cli<1,>=0.8.7
# #9 2.749   Downloading databricks-cli-0.17.6.tar.gz (82 kB)
# #9 2.756      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.7/82.7 kB 14.6 MB/s eta 0:00:00
# #9 2.779   Preparing metadata (setup.py): started
# #9 3.248   Preparing metadata (setup.py): finished with status 'done'
# #9 3.291 Collecting alembic<2
# #9 3.303   Downloading alembic-1.10.2-py3-none-any.whl (212 kB)
# #9 3.323      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.2/212.2 kB 12.8 MB/s eta 0:00:00
# #9 3.496 Collecting pandas<3
# #9 3.518   Downloading pandas-1.5.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.1 MB)
# #9 4.484      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 12.6 MB/s eta 0:00:00
# #9 4.531 Collecting gunicorn<21
# #9 4.542   Downloading gunicorn-20.1.0-py3-none-any.whl (79 kB)
# #9 4.549      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 15.4 MB/s eta 0:00:00
# #9 4.585 Collecting cloudpickle<3
# #9 4.598   Downloading cloudpickle-2.2.1-py3-none-any.whl (25 kB)
# #9 4.721 Collecting scikit-learn<2
# #9 4.737   Downloading scikit_learn-1.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.6 MB)
# #9 5.572      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 11.6 MB/s eta 0:00:00
# #9 5.656 Collecting click<9,>=7.0
# #9 5.669   Downloading click-8.1.3-py3-none-any.whl (96 kB)
# #9 5.679      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 kB 10.9 MB/s eta 0:00:00
# #9 5.696 Collecting entrypoints<1
# #9 5.710   Downloading entrypoints-0.4-py3-none-any.whl (5.3 kB)
# #9 5.739 Collecting packaging<24
# #9 5.748   Downloading packaging-23.0-py3-none-any.whl (42 kB)
# #9 5.753      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.7/42.7 kB 15.1 MB/s eta 0:00:00
# #9 5.850 Collecting querystring-parser<2
# #9 5.862   Downloading querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
# #9 5.962 Collecting pyarrow<12,>=4.0.0
# #9 5.977   Downloading pyarrow-11.0.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.9 MB)
# #9 8.761      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.9/34.9 MB 12.1 MB/s eta 0:00:00
# #9 8.825 Collecting Flask<3
# #9 8.847   Downloading Flask-2.2.3-py3-none-any.whl (101 kB)
# #9 8.857      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.8/101.8 kB 12.4 MB/s eta 0:00:00
# #9 8.902 Collecting requests<3,>=2.17.3
# #9 8.913   Downloading requests-2.28.2-py3-none-any.whl (62 kB)
# #9 8.921      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 13.5 MB/s eta 0:00:00
# #9 9.310 Collecting sqlalchemy<3,>=1.4.0
# #9 9.326   Downloading SQLAlchemy-2.0.8-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.7 MB)
# #9 9.552      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 12.2 MB/s eta 0:00:00
# #9 9.706 Collecting shap<1,>=0.40
# #9 9.717   Downloading shap-0.41.0-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (572 kB)
# #9 9.767      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 572.6/572.6 kB 12.5 MB/s eta 0:00:00
# #9 10.00 Collecting protobuf<5,>=3.12.0
# #9 10.02   Downloading protobuf-4.22.1-cp37-abi3-manylinux2014_x86_64.whl (302 kB)
# #9 10.04      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.4/302.4 kB 13.2 MB/s eta 0:00:00
# #9 10.09 Collecting gitpython<4,>=2.1.0
# #9 10.10   Downloading GitPython-3.1.31-py3-none-any.whl (184 kB)
# #9 10.12      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 184.3/184.3 kB 12.2 MB/s eta 0:00:00
# #9 10.28 Collecting scipy<2
# #9 10.29   Downloading scipy-1.10.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.4 MB)
# #9 13.01      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.4/34.4 MB 12.5 MB/s eta 0:00:00
# #9 13.13 Collecting pytz<2023
# #9 13.14   Downloading pytz-2022.7.1-py2.py3-none-any.whl (499 kB)
# #9 13.19      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 499.4/499.4 kB 11.7 MB/s eta 0:00:00
# #9 13.39 Collecting matplotlib<4
# #9 13.41   Downloading matplotlib-3.7.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.6 MB)
# #9 14.36      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 12.3 MB/s eta 0:00:00
# #9 14.66 Collecting numpy<2
# #9 14.68   Downloading numpy-1.24.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
# #9 16.07      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 12.8 MB/s eta 0:00:00
# #9 16.11 Collecting sqlparse<1,>=0.4.0
# #9 16.12   Downloading sqlparse-0.4.3-py3-none-any.whl (42 kB)
# #9 16.12      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.8/42.8 kB 35.8 MB/s eta 0:00:00
# #9 16.15 Collecting markdown<4,>=3.3
# #9 16.17   Downloading Markdown-3.4.3-py3-none-any.whl (93 kB)
# #9 16.18      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.9/93.9 kB 11.3 MB/s eta 0:00:00
# #9 16.21 Collecting Jinja2<4,>=2.11
# #9 16.23   Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
# #9 16.24      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 15.9 MB/s eta 0:00:00
# #9 16.29 Collecting docker<7,>=4.0.0
# #9 16.30   Downloading docker-6.0.1-py3-none-any.whl (147 kB)
# #9 16.31      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.5/147.5 kB 12.4 MB/s eta 0:00:00
# #9 16.40 Collecting importlib-metadata!=4.7.0,<7,>=3.7.0
# #9 16.41   Downloading importlib_metadata-6.1.0-py3-none-any.whl (21 kB)
# #9 16.46 Collecting Mako
# #9 16.47   Downloading Mako-1.2.4-py3-none-any.whl (78 kB)
# #9 16.48      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.7/78.7 kB 18.1 MB/s eta 0:00:00
# #9 16.51 Collecting typing-extensions>=4
# #9 16.52   Downloading typing_extensions-4.5.0-py3-none-any.whl (27 kB)
# #9 16.55 Collecting pyjwt>=1.7.0
# #9 16.57   Downloading PyJWT-2.6.0-py3-none-any.whl (20 kB)
# #9 16.60 Collecting oauthlib>=3.1.0
# #9 16.61   Downloading oauthlib-3.2.2-py3-none-any.whl (151 kB)
# #9 16.76      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 151.7/151.7 kB 1.1 MB/s eta 0:00:00
# #9 16.78 Collecting tabulate>=0.7.7
# #9 16.79   Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
# #9 16.83 Collecting six>=1.10.0
# #9 16.84   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
# #9 16.88 Collecting websocket-client>=0.32.0
# #9 16.89   Downloading websocket_client-1.5.1-py3-none-any.whl (55 kB)
# #9 16.89      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.9/55.9 kB 33.1 MB/s eta 0:00:00
# #9 16.94 Collecting urllib3>=1.26.0
# #9 16.95   Downloading urllib3-1.26.15-py2.py3-none-any.whl (140 kB)
# #9 16.96      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.9/140.9 kB 15.8 MB/s eta 0:00:00
# #9 17.02 Collecting Werkzeug>=2.2.2
# #9 17.03   Downloading Werkzeug-2.2.3-py3-none-any.whl (233 kB)
# #9 17.06      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.6/233.6 kB 10.0 MB/s eta 0:00:00
# #9 17.08 Collecting itsdangerous>=2.0
# #9 17.09   Downloading itsdangerous-2.1.2-py3-none-any.whl (15 kB)
# #9 17.12 Collecting gitdb<5,>=4.0.1
# #9 17.13   Downloading gitdb-4.0.10-py3-none-any.whl (62 kB)
# #9 17.14      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 15.9 MB/s eta 0:00:00
# #9 17.14 Requirement already satisfied: setuptools>=3.0 in /usr/local/lib/python3.10/site-packages (from gunicorn<21->mlflow==2.2.1->-r requirements.txt (line 1)) (65.5.1)
# #9 17.19 Collecting zipp>=0.5
# #9 17.21   Downloading zipp-3.15.0-py3-none-any.whl (6.8 kB)
# #9 17.27 Collecting MarkupSafe>=2.0
# #9 17.30   Downloading MarkupSafe-2.1.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
# #9 17.33 Collecting cycler>=0.10
# #9 17.34   Downloading cycler-0.11.0-py3-none-any.whl (6.4 kB)
# #9 17.41 Collecting fonttools>=4.22.0
# #9 17.42   Downloading fonttools-4.39.3-py3-none-any.whl (1.0 MB)
# #9 17.50      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 12.4 MB/s eta 0:00:00
# #9 17.55 Collecting pyparsing>=2.3.1
# #9 17.56   Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
# #9 17.57      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.3/98.3 kB 12.7 MB/s eta 0:00:00
# #9 17.63 Collecting kiwisolver>=1.0.1
# #9 17.67   Downloading kiwisolver-1.4.4-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
# #9 17.80      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 12.5 MB/s eta 0:00:00
# #9 17.83 Collecting python-dateutil>=2.7
# #9 17.84   Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
# #9 17.86      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 13.2 MB/s eta 0:00:00
# #9 18.18 Collecting pillow>=6.2.0
# #9 18.20   Downloading Pillow-9.5.0-cp310-cp310-manylinux_2_28_x86_64.whl (3.4 MB)
# #9 18.49      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 11.9 MB/s eta 0:00:00
# #9 18.59 Collecting contourpy>=1.0.1
# #9 18.60   Downloading contourpy-1.0.7-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (300 kB)
# #9 18.63      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 300.3/300.3 kB 12.2 MB/s eta 0:00:00
# #9 18.76 Collecting idna<4,>=2.5
# #9 18.77   Downloading idna-3.4-py3-none-any.whl (61 kB)
# #9 18.78      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 22.1 MB/s eta 0:00:00
# #9 18.86 Collecting charset-normalizer<4,>=2
# #9 18.87   Downloading charset_normalizer-3.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (199 kB)
# #9 18.89      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.3/199.3 kB 12.6 MB/s eta 0:00:00
# #9 18.92 Collecting certifi>=2017.4.17
# #9 18.93   Downloading certifi-2022.12.7-py3-none-any.whl (155 kB)
# #9 18.95      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.3/155.3 kB 11.4 MB/s eta 0:00:00
# #9 18.99 Collecting threadpoolctl>=2.0.0
# #9 19.00   Downloading threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
# #9 19.04 Collecting joblib>=1.1.1
# #9 19.05   Downloading joblib-1.2.0-py3-none-any.whl (297 kB)
# #9 19.07      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.0/298.0 kB 13.3 MB/s eta 0:00:00
# #9 19.22 Collecting tqdm>4.25.0
# #9 19.23   Downloading tqdm-4.65.0-py3-none-any.whl (77 kB)
# #9 19.24      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.1/77.1 kB 22.5 MB/s eta 0:00:00
# #9 19.39 Collecting numba
# #9 19.41   Downloading numba-0.56.4-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.5 MB)
# #9 19.70      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 12.2 MB/s eta 0:00:00
# #9 19.81 Collecting slicer==0.0.7
# #9 19.82   Downloading slicer-0.0.7-py3-none-any.whl (14 kB)
# #9 20.02 Collecting greenlet!=0.4.17
# #9 20.04   Downloading greenlet-2.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (613 kB)
# #9 20.09      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 613.7/613.7 kB 17.8 MB/s eta 0:00:00
# #9 20.19 Collecting smmap<6,>=3.0.1
# #9 20.20   Downloading smmap-5.0.0-py3-none-any.whl (24 kB)
# #9 20.48 Collecting llvmlite<0.40,>=0.39.0dev0
# #9 20.49   Downloading llvmlite-0.39.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.6 MB)
# #9 23.35      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.6/34.6 MB 12.3 MB/s eta 0:00:00
# #9 23.40 Collecting numpy<2
# #9 23.41   Downloading numpy-1.23.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
# #9 24.83      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 11.7 MB/s eta 0:00:00
# #9 24.93 Building wheels for collected packages: databricks-cli
# #9 24.93   Building wheel for databricks-cli (setup.py): started
# #9 25.28   Building wheel for databricks-cli (setup.py): finished with status 'done'
# #9 25.28   Created wheel for databricks-cli: filename=databricks_cli-0.17.6-py3-none-any.whl size=143221 sha256=c239efd75717ae15fee6ee0e9b022e4c335646488be3074cb69091c4224c1136
# #9 25.28   Stored in directory: /tmp/pip-ephem-wheel-cache-_k03b1rn/wheels/7b/85/a1/37b9b24f55c1da8ea4795765de41713b8a2cccad89c866e26b
# #9 25.29 Successfully built databricks-cli
# #9 25.63 Installing collected packages: pytz, zipp, websocket-client, urllib3, typing-extensions, tqdm, threadpoolctl, tabulate, sqlparse, smmap, slicer, six, pyyaml, pyparsing, pymysql, pyjwt, protobuf, pillow, packaging, oauthlib, numpy, MarkupSafe, markdown, llvmlite, kiwisolver, joblib, itsdangerous, idna, gunicorn, greenlet, fonttools, entrypoints, cycler, cloudpickle, click, charset-normalizer, certifi, Werkzeug, sqlalchemy, scipy, requests, querystring-parser, python-dateutil, pyarrow, numba, Mako, Jinja2, importlib-metadata, gitdb, contourpy, scikit-learn, pandas, matplotlib, gitpython, Flask, docker, databricks-cli, alembic, shap, mlflow
# #9 54.75 Successfully installed Flask-2.2.3 Jinja2-3.1.2 Mako-1.2.4 MarkupSafe-2.1.2 Werkzeug-2.2.3 alembic-1.10.2 certifi-2022.12.7 charset-normalizer-3.1.0 click-8.1.3 cloudpickle-2.2.1 contourpy-1.0.7 cycler-0.11.0 databricks-cli-0.17.6 docker-6.0.1 entrypoints-0.4 fonttools-4.39.3 gitdb-4.0.10 gitpython-3.1.31 greenlet-2.0.2 gunicorn-20.1.0 idna-3.4 importlib-metadata-6.1.0 itsdangerous-2.1.2 joblib-1.2.0 kiwisolver-1.4.4 llvmlite-0.39.1 markdown-3.4.3 matplotlib-3.7.1 mlflow-2.2.1 numba-0.56.4 numpy-1.23.5 oauthlib-3.2.2 packaging-23.0 pandas-1.5.3 pillow-9.5.0 protobuf-4.22.1 pyarrow-11.0.0 pyjwt-2.6.0 pymysql-1.0.3 pyparsing-3.0.9 python-dateutil-2.8.2 pytz-2022.7.1 pyyaml-6.0 querystring-parser-1.2.4 requests-2.28.2 scikit-learn-1.2.2 scipy-1.10.1 shap-0.41.0 six-1.16.0 slicer-0.0.7 smmap-5.0.0 sqlalchemy-2.0.8 sqlparse-0.4.3 tabulate-0.9.0 threadpoolctl-3.1.0 tqdm-4.65.0 typing-extensions-4.5.0 urllib3-1.26.15 websocket-client-1.5.1 zipp-3.15.0
# #9 54.75 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
# #9 DONE 63.0s
#
# #11 exporting to image
# #11 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
# #11 exporting layers
# #11 exporting layers 3.8s done
# #11 writing image sha256:c80c138b84b83b811a413a62aa846bd14e9698346289e486b023227bcb0b94dc 0.0s done
# #11 naming to docker.io/library/mlflow_tracker_slim_as_root 0.0s done
# #11 DONE 3.9s