# Good practice: Use official base images
#
FROM continuumio/miniconda3:latest

# Good practice: upgrade distro packages (with last security patches).
#
RUN apt-get update && apt-get -y upgrade \
    && apt-get install -y procps \
    && pip install --upgrade pip \
    && pip --version \
    && conda update -n base -c defaults conda \
    && conda --version \
    && conda info

# Good practice: don't run things in containers as root.
#
RUN groupadd gustavo && useradd --create-home -g gustavo gustavo
ENV PATH /home/gustavo/.local/bin:${PATH}

# Good practice: install the app under the appuser home folder:
#
WORKDIR /home/gustavo

# Copy the code to run when container is started
#
COPY ./entrypoint-conda-dev.sh .
RUN chown gustavo ./entrypoint-conda-dev.sh \
    && chmod u+x ./entrypoint-conda-dev.sh

# From now on, this process is owned by gustavo:
#
USER gustavo

# Create the environment:
#
COPY ./conda.yml .
RUN conda env create -f conda.yml

# We need to 'conda run' activating the env 'mlflow_env' before calling '/bin/bash ./entrypoint.sh':
#
ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "mlflow_env", "/bin/bash", "./entrypoint-conda-dev.sh"]


# ======================================================================================================================================
# VERBOSE Image build:
# ======================================================================================================================================

# Build the image with:

# $ docker build -f Dockerfile-conda --progress plain --no-cache -t mlflow_tracker_conda .

# Logged info:

# #1 [internal] load build definition from Dockerfile-conda
# #1 sha256:e902a6f1828659da25bb5e8270d0a1773e6df4d10b47ee12e897439fc3714531
# #1 transferring dockerfile: 45B done
# #1 DONE 0.1s

# #2 [internal] load .dockerignore
# #2 sha256:50cad559b5ebd8b33b50a7702d8bf4b89b28cbfcaacc6918d4dcba8cb2dbb1e3
# #2 transferring context: 35B done
# #2 DONE 0.1s

# #3 [internal] load metadata for docker.io/continuumio/miniconda3:latest
# #3 sha256:70c01be2623751a8f6df5d5b392c0445964bc863c94f2ca91c3dab835106ad61
# #3 DONE 0.6s

# #4 [1/8] FROM docker.io/continuumio/miniconda3:latest@sha256:10b38c9a8a51692838ce4517e8c74515499b68d58c8a2000d8a9df7f0f08fc5e
# #4 sha256:ccd4c77176649410f666e8c9fea0b32651e5bc2bcdb6a66740827c55b8c662cd
# #4 CACHED

# #8 [internal] load build context
# #8 sha256:f1be08452e7fe3400d379dfe6d409e04951430fc96aa1097cf9775843da97ac5
# #8 transferring context: 64B done
# #8 DONE 0.0s

# #5 [2/8] RUN apt-get update && apt-get -y upgrade     && conda update -n base -c defaults conda     && conda --version     && conda info
# #5 sha256:757221556e856dbb0de0f915edf45c28951b0d24861e95049b809f701ed6caf6
# #5 0.398 Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
# #5 0.430 Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
# #5 0.441 Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
# #5 0.502 Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8183 kB]
# #5 1.180 Get:5 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [236 kB]
# #5 1.201 Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [14.6 kB]
# #5 1.920 Fetched 8642 kB in 2s (5610 kB/s)
# #5 1.920 Reading package lists...
# #5 2.278 Reading package lists...
# #5 2.603 Building dependency tree...
# #5 2.681 Reading state information...
# #5 2.693 Calculating upgrade...
# #5 2.794 The following packages will be upgraded:
# #5 2.794   git git-man libapr1 libaprutil1 libcurl3-gnutls libgnutls30 libssl1.1
# #5 2.794   openssl tzdata
# #5 2.822 9 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
# #5 2.822 Need to get 11.9 MB of archives.
# #5 2.822 After this operation, 55.3 kB of additional disk space will be used.
# #5 2.822 Get:1 http://deb.debian.org/debian-security bullseye-security/main amd64 libgnutls30 amd64 3.7.1-5+deb11u3 [1340 kB]
# #5 2.957 Get:2 http://deb.debian.org/debian-security bullseye-security/main amd64 libssl1.1 amd64 1.1.1n-0+deb11u4 [1560 kB]
# #5 3.077 Get:3 http://deb.debian.org/debian bullseye-updates/main amd64 tzdata all 2021a-1+deb11u9 [286 kB]
# #5 3.099 Get:4 http://deb.debian.org/debian-security bullseye-security/main amd64 git-man all 1:2.30.2-1+deb11u2 [1828 kB]
# #5 3.235 Get:5 http://deb.debian.org/debian-security bullseye-security/main amd64 libcurl3-gnutls amd64 7.74.0-1.3+deb11u7 [343 kB]
# #5 3.260 Get:6 http://deb.debian.org/debian-security bullseye-security/main amd64 git amd64 1:2.30.2-1+deb11u2 [5518 kB]
# #5 3.662 Get:7 http://deb.debian.org/debian-security bullseye-security/main amd64 libaprutil1 amd64 1.6.1-5+deb11u1 [92.3 kB]
# #5 3.668 Get:8 http://deb.debian.org/debian-security bullseye-security/main amd64 libapr1 amd64 1.7.0-6+deb11u2 [106 kB]
# #5 3.676 Get:9 http://deb.debian.org/debian-security bullseye-security/main amd64 openssl amd64 1.1.1n-0+deb11u4 [853 kB]
# #5 3.840 debconf: delaying package configuration, since apt-utils is not installed
# #5 3.867 Fetched 11.9 MB in 1s (12.6 MB/s)
# (Reading database ... 12440 files and directories currently installed.)
# #5 3.899 Preparing to unpack .../libgnutls30_3.7.1-5+deb11u3_amd64.deb ...
# #5 3.916 Unpacking libgnutls30:amd64 (3.7.1-5+deb11u3) over (3.7.1-5+deb11u2) ...
# #5 4.050 Setting up libgnutls30:amd64 (3.7.1-5+deb11u3) ...
# (Reading database ... 12440 files and directories currently installed.)
# #5 4.099 Preparing to unpack .../libssl1.1_1.1.1n-0+deb11u4_amd64.deb ...
# #5 4.111 Unpacking libssl1.1:amd64 (1.1.1n-0+deb11u4) over (1.1.1n-0+deb11u3) ...
# #5 4.284 Setting up libssl1.1:amd64 (1.1.1n-0+deb11u4) ...
# #5 4.336 debconf: unable to initialize frontend: Dialog
# #5 4.336 debconf: (TERM is not set, so the dialog frontend is not usable.)
# #5 4.336 debconf: falling back to frontend: Readline
# (Reading database ... 12440 files and directories currently installed.)
# #5 4.402 Preparing to unpack .../0-tzdata_2021a-1+deb11u9_all.deb ...
# #5 4.413 Unpacking tzdata (2021a-1+deb11u9) over (2021a-1+deb11u8) ...
# #5 7.153 Preparing to unpack .../1-git-man_1%3a2.30.2-1+deb11u2_all.deb ...
# #5 7.164 Unpacking git-man (1:2.30.2-1+deb11u2) over (1:2.30.2-1) ...
# #5 7.274 Preparing to unpack .../2-libcurl3-gnutls_7.74.0-1.3+deb11u7_amd64.deb ...
# #5 7.285 Unpacking libcurl3-gnutls:amd64 (7.74.0-1.3+deb11u7) over (7.74.0-1.3+deb11u3) ...
# #5 7.354 Preparing to unpack .../3-git_1%3a2.30.2-1+deb11u2_amd64.deb ...
# #5 7.385 Unpacking git (1:2.30.2-1+deb11u2) over (1:2.30.2-1) ...
# #5 8.224 Preparing to unpack .../4-libaprutil1_1.6.1-5+deb11u1_amd64.deb ...
# #5 8.235 Unpacking libaprutil1:amd64 (1.6.1-5+deb11u1) over (1.6.1-5) ...
# #5 8.289 Preparing to unpack .../5-libapr1_1.7.0-6+deb11u2_amd64.deb ...
# #5 8.300 Unpacking libapr1:amd64 (1.7.0-6+deb11u2) over (1.7.0-6+deb11u1) ...
# #5 8.350 Preparing to unpack .../6-openssl_1.1.1n-0+deb11u4_amd64.deb ...
# #5 8.361 Unpacking openssl (1.1.1n-0+deb11u4) over (1.1.1n-0+deb11u3) ...
# #5 8.453 Setting up libapr1:amd64 (1.7.0-6+deb11u2) ...
# #5 8.466 Setting up libcurl3-gnutls:amd64 (7.74.0-1.3+deb11u7) ...
# #5 8.477 Setting up tzdata (2021a-1+deb11u9) ...
# #5 8.525 debconf: unable to initialize frontend: Dialog
# #5 8.525 debconf: (TERM is not set, so the dialog frontend is not usable.)
# #5 8.525 debconf: falling back to frontend: Readline
# #5 8.556
# #5 8.556 Current default time zone: 'Etc/UTC'
# #5 8.558 Local time is now:      Sat Apr  1 11:28:14 UTC 2023.
# #5 8.558 Universal Time is now:  Sat Apr  1 11:28:14 UTC 2023.
# #5 8.558 Run 'dpkg-reconfigure tzdata' if you wish to change it.
# #5 8.558
# #5 8.574 Setting up git-man (1:2.30.2-1+deb11u2) ...
# #5 8.587 Setting up openssl (1.1.1n-0+deb11u4) ...
# #5 8.602 Setting up libaprutil1:amd64 (1.6.1-5+deb11u1) ...
# #5 8.617 Setting up git (1:2.30.2-1+deb11u2) ...
# #5 8.641 Processing triggers for libc-bin (2.31-13+deb11u5) ...
# #5 9.048 Collecting package metadata (current_repodata.json): ...working... done
# #5 11.30 Solving environment: ...working... done
# #5 12.76
# #5 12.76 ## Package Plan ##
# #5 12.76
# #5 12.76   environment location: /opt/conda
# #5 12.76
# #5 12.76   added / updated specs:
# #5 12.76     - conda
# #5 12.76
# #5 12.76
# #5 12.76 The following packages will be downloaded:
# #5 12.76
# #5 12.76     package                    |            build
# #5 12.76     ---------------------------|-----------------
# #5 12.76     boltons-23.0.0             |  py310h06a4308_0         430 KB
# #5 12.76     ca-certificates-2023.01.10 |       h06a4308_0         120 KB
# #5 12.76     conda-23.3.1               |  py310h06a4308_0         970 KB
# #5 12.76     conda-package-handling-2.0.2|  py310h06a4308_0         267 KB
# #5 12.76     conda-package-streaming-0.7.0|  py310h06a4308_0          27 KB
# #5 12.76     cryptography-39.0.1        |  py310h9ce1e76_0         1.4 MB
# #5 12.76     jsonpatch-1.32             |     pyhd3eb1b0_0          15 KB
# #5 12.76     jsonpointer-2.1            |     pyhd3eb1b0_0           9 KB
# #5 12.76     ncurses-6.4                |       h6a678d5_0         914 KB
# #5 12.76     openssl-1.1.1t             |       h7f8727e_0         3.7 MB
# #5 12.76     packaging-23.0             |  py310h06a4308_0          68 KB
# #5 12.76     pyopenssl-23.0.0           |  py310h06a4308_0          97 KB
# #5 12.76     requests-2.28.1            |  py310h06a4308_1         100 KB
# #5 12.76     sqlite-3.41.1              |       h5eee18b_0         1.2 MB
# #5 12.76     tqdm-4.65.0                |  py310h2f386ee_0         132 KB
# #5 12.76     urllib3-1.26.15            |  py310h06a4308_0         199 KB
# #5 12.76     xz-5.2.10                  |       h5eee18b_1         429 KB
# #5 12.76     zstandard-0.19.0           |  py310h5eee18b_0         474 KB
# #5 12.76     ------------------------------------------------------------
# #5 12.76                                            Total:        10.5 MB
# #5 12.76
# #5 12.76 The following NEW packages will be INSTALLED:
# #5 12.76
# #5 12.76   boltons            pkgs/main/linux-64::boltons-23.0.0-py310h06a4308_0
# #5 12.76   conda-package-str~ pkgs/main/linux-64::conda-package-streaming-0.7.0-py310h06a4308_0
# #5 12.76   jsonpatch          pkgs/main/noarch::jsonpatch-1.32-pyhd3eb1b0_0
# #5 12.76   jsonpointer        pkgs/main/noarch::jsonpointer-2.1-pyhd3eb1b0_0
# #5 12.76   packaging          pkgs/main/linux-64::packaging-23.0-py310h06a4308_0
# #5 12.76   zstandard          pkgs/main/linux-64::zstandard-0.19.0-py310h5eee18b_0
# #5 12.76
# #5 12.76 The following packages will be UPDATED:
# #5 12.76
# #5 12.76   ca-certificates                     2022.10.11-h06a4308_0 --> 2023.01.10-h06a4308_0
# #5 12.76   conda                             22.11.1-py310h06a4308_4 --> 23.3.1-py310h06a4308_0
# #5 12.76   conda-package-han~                  1.9.0-py310h5eee18b_1 --> 2.0.2-py310h06a4308_0
# #5 12.76   cryptography                       38.0.1-py310h9ce1e76_0 --> 39.0.1-py310h9ce1e76_0
# #5 12.76   ncurses                                    6.3-h5eee18b_3 --> 6.4-h6a678d5_0
# #5 12.76   openssl                                 1.1.1s-h7f8727e_0 --> 1.1.1t-h7f8727e_0
# #5 12.76   pyopenssl          pkgs/main/noarch::pyopenssl-22.0.0-py~ --> pkgs/main/linux-64::pyopenssl-23.0.0-py310h06a4308_0
# #5 12.76   requests                           2.28.1-py310h06a4308_0 --> 2.28.1-py310h06a4308_1
# #5 12.76   sqlite                                  3.40.0-h5082296_0 --> 3.41.1-h5eee18b_0
# #5 12.76   tqdm                               4.64.1-py310h06a4308_0 --> 4.65.0-py310h2f386ee_0
# #5 12.76   urllib3                           1.26.13-py310h06a4308_0 --> 1.26.15-py310h06a4308_0
# #5 12.76   xz                                       5.2.8-h5eee18b_0 --> 5.2.10-h5eee18b_1
# #5 12.76
# #5 12.76
# #5 12.76 Proceed ([y]/n)?
# #5 12.76
# #5 12.76 Downloading and Extracting Packages

# #5 13.78 Preparing transaction: ...working... done
# #5 13.92 Verifying transaction: ...working... done
# #5 14.37 Executing transaction: ...working... done
# #5 22.99 conda 23.3.1
# #5 23.56
# #5 23.56      active environment : None
# #5 23.56        user config file : /root/.condarc
# #5 23.56  populated config files :
# #5 23.56           conda version : 23.3.1
# #5 23.56     conda-build version : not installed
# #5 23.56          python version : 3.10.8.final.0
# #5 23.56        virtual packages : __archspec=1=x86_64
# #5 23.56                           __glibc=2.31=0
# #5 23.56                           __linux=5.15.90.1=0
# #5 23.56                           __unix=0=0
# #5 23.56        base environment : /opt/conda  (writable)
# #5 23.56       conda av data dir : /opt/conda/etc/conda
# #5 23.56   conda av metadata url : None
# #5 23.56            channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
# #5 23.56                           https://repo.anaconda.com/pkgs/main/noarch
# #5 23.56                           https://repo.anaconda.com/pkgs/r/linux-64
# #5 23.56                           https://repo.anaconda.com/pkgs/r/noarch
# #5 23.56           package cache : /opt/conda/pkgs
# #5 23.56                           /root/.conda/pkgs
# #5 23.56        envs directories : /opt/conda/envs
# #5 23.56                           /root/.conda/envs
# #5 23.56                platform : linux-64
# #5 23.56              user-agent : conda/23.3.1 requests/2.28.1 CPython/3.10.8 Linux/5.15.90.1-microsoft-standard-WSL2 debian/11 glibc/2.31
# #5 23.56                 UID:GID : 0:0
# #5 23.56              netrc file : None
# #5 23.56            offline mode : False
# #5 23.56
# #5 DONE 23.9s

# #6 [3/8] RUN groupadd mlflow && useradd --create-home -g mlflow gustavo
# #6 sha256:2f635e0b17b6c95d2dbb74bf29d6b20f02cc8d1cacd824a0ec98d98fb24db515
# #6 DONE 0.5s

# #7 [4/8] WORKDIR /home/gustavo
# #7 sha256:3ebff74273493c7990df5ee4b9bb805d10127e8383b00e7280038d9b78bea952
# #7 DONE 0.0s

# #9 [5/8] COPY ./entrypoint.sh .
# #9 sha256:d27f89c70f21531e82b6e37e7ff8ccec465b18ea4514ef571449515c2514f8af
# #9 DONE 0.0s

# #10 [6/8] RUN chown gustavo ./entrypoint.sh     && chmod u+x ./entrypoint.sh
# #10 sha256:8589d09a83040e7c0a9beebdedfad9806e80899a65906b625dfb5b4358295f2b
# #10 DONE 0.5s

# #11 [7/8] COPY ./conda.yml .
# #11 sha256:21bccc7bf61f2a5fedb36d1013b30939e99ac8c8158a1a9760f6df31bbfaf32f
# #11 DONE 0.1s

# #12 [8/8] RUN conda env create -f conda.yml
# #12 sha256:88fc29c848af11adbbea5a7523c08d9087160d1b27e08bb46bda8c3b2e9037c0
# #12 0.932 Collecting package metadata (repodata.json): ...working... done
# #12 72.66 Solving environment: ...working... done
# #12 74.96
# #12 74.96 Downloading and Extracting Packages

# #12 79.66 Preparing transaction: ...working... done
# #12 79.85 Verifying transaction: ...working... done
# #12 80.60 Executing transaction: ...working... done
# #12 82.47 Installing pip dependencies: ...working... Ran pip subprocess with arguments:
# #12 122.5 ['/home/gustavo/.conda/envs/mlflow_env/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/gustavo/condaenv.ovf906j9.requirements.txt', '--exists-action=b']
# #12 122.5 Pip subprocess output:
# #12 122.5 Collecting mlflow<3,>=2.1
# #12 122.5   Downloading mlflow-2.2.2-py3-none-any.whl (17.6 MB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.6/17.6 MB 11.3 MB/s eta 0:00:00
# #12 122.5 Collecting pymysql
# #12 122.5   Downloading PyMySQL-1.0.3-py3-none-any.whl (43 kB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 1.5 MB/s eta 0:00:00
# #12 122.5 Collecting gunicorn<21
# #12 122.5   Downloading gunicorn-20.1.0-py3-none-any.whl (79 kB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 8.6 MB/s eta 0:00:00
# #12 122.5 Collecting numpy<2
# #12 122.5   Downloading numpy-1.24.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 12.9 MB/s eta 0:00:00
# #12 122.5 Collecting docker<7,>=4.0.0
# #12 122.5   Downloading docker-6.0.1-py3-none-any.whl (147 kB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.5/147.5 kB 10.1 MB/s eta 0:00:00
# #12 122.5 Collecting Jinja2<4,>=2.11
# #12 122.5   Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 9.3 MB/s eta 0:00:00
# #12 122.5 Collecting protobuf<5,>=3.12.0
# #12 122.5   Downloading protobuf-4.22.1-cp37-abi3-manylinux2014_x86_64.whl (302 kB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.4/302.4 kB 6.2 MB/s eta 0:00:00
# #12 122.5 Collecting gitpython<4,>=2.1.0
# #12 122.5   Downloading GitPython-3.1.31-py3-none-any.whl (184 kB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 184.3/184.3 kB 9.4 MB/s eta 0:00:00
# #12 122.5 Collecting matplotlib<4
# #12 122.5   Downloading matplotlib-3.7.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.6 MB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 13.3 MB/s eta 0:00:00
# #12 122.5 Collecting packaging<24
# #12 122.5   Downloading packaging-23.0-py3-none-any.whl (42 kB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.7/42.7 kB 6.5 MB/s eta 0:00:00
# #12 122.5 Collecting pytz<2023
# #12 122.5   Downloading pytz-2022.7.1-py2.py3-none-any.whl (499 kB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 499.4/499.4 kB 11.4 MB/s eta 0:00:00
# #12 122.5 Collecting pyarrow<12,>=4.0.0
# #12 122.5   Downloading pyarrow-11.0.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.9 MB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.9/34.9 MB 12.2 MB/s eta 0:00:00
# #12 122.5 Collecting Flask<3
# #12 122.5   Downloading Flask-2.2.3-py3-none-any.whl (101 kB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.8/101.8 kB 8.5 MB/s eta 0:00:00
# #12 122.5 Collecting scipy<2
# #12 122.5   Downloading scipy-1.10.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.4 MB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.4/34.4 MB 11.6 MB/s eta 0:00:00
# #12 122.5 Collecting sqlalchemy<3,>=1.4.0
# #12 122.5   Downloading SQLAlchemy-2.0.8-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.7 MB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 12.6 MB/s eta 0:00:00
# #12 122.5 Collecting pyyaml<7,>=5.1
# #12 122.5   Downloading PyYAML-6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (682 kB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 682.2/682.2 kB 11.7 MB/s eta 0:00:00
# #12 122.5 Collecting click<9,>=7.0
# #12 122.5   Downloading click-8.1.3-py3-none-any.whl (96 kB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 kB 6.7 MB/s eta 0:00:00
# #12 122.5 Collecting markdown<4,>=3.3
# #12 122.5   Downloading Markdown-3.4.3-py3-none-any.whl (93 kB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.9/93.9 kB 7.3 MB/s eta 0:00:00
# #12 122.5 Collecting importlib-metadata!=4.7.0,<7,>=3.7.0
# #12 122.5   Downloading importlib_metadata-6.1.0-py3-none-any.whl (21 kB)
# #12 122.5 Collecting databricks-cli<1,>=0.8.7
# #12 122.5   Downloading databricks-cli-0.17.6.tar.gz (82 kB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.7/82.7 kB 9.0 MB/s eta 0:00:00
# #12 122.5   Preparing metadata (setup.py): started
# #12 122.5   Preparing metadata (setup.py): finished with status 'done'
# #12 122.5 Collecting shap<1,>=0.40
# #12 122.5   Downloading shap-0.41.0-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (572 kB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 572.6/572.6 kB 11.2 MB/s eta 0:00:00
# #12 122.5 Collecting entrypoints<1
# #12 122.5   Downloading entrypoints-0.4-py3-none-any.whl (5.3 kB)
# #12 122.5 Collecting scikit-learn<2
# #12 122.5   Downloading scikit_learn-1.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.6 MB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 13.0 MB/s eta 0:00:00
# #12 122.5 Collecting requests<3,>=2.17.3
# #12 122.5   Downloading requests-2.28.2-py3-none-any.whl (62 kB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 8.2 MB/s eta 0:00:00
# #12 122.5 Collecting sqlparse<1,>=0.4.0
# #12 122.5   Downloading sqlparse-0.4.3-py3-none-any.whl (42 kB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.8/42.8 kB 5.5 MB/s eta 0:00:00
# #12 122.5 Collecting pandas<3
# #12 122.5   Downloading pandas-1.5.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.1 MB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 13.0 MB/s eta 0:00:00
# #12 122.5 Collecting cloudpickle<3
# #12 122.5   Downloading cloudpickle-2.2.1-py3-none-any.whl (25 kB)
# #12 122.5 Collecting querystring-parser<2
# #12 122.5   Downloading querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
# #12 122.5 Collecting alembic<2
# #12 122.5   Downloading alembic-1.10.2-py3-none-any.whl (212 kB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.2/212.2 kB 8.6 MB/s eta 0:00:00
# #12 122.5 Collecting Mako
# #12 122.5   Downloading Mako-1.2.4-py3-none-any.whl (78 kB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.7/78.7 kB 9.4 MB/s eta 0:00:00
# #12 122.5 Collecting typing-extensions>=4
# #12 122.5   Downloading typing_extensions-4.5.0-py3-none-any.whl (27 kB)
# #12 122.5 Collecting pyjwt>=1.7.0
# #12 122.5   Downloading PyJWT-2.6.0-py3-none-any.whl (20 kB)
# #12 122.5 Collecting oauthlib>=3.1.0
# #12 122.5   Downloading oauthlib-3.2.2-py3-none-any.whl (151 kB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 151.7/151.7 kB 10.9 MB/s eta 0:00:00
# #12 122.5 Collecting tabulate>=0.7.7
# #12 122.5   Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
# #12 122.5 Collecting six>=1.10.0
# #12 122.5   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
# #12 122.5 Collecting urllib3>=1.26.0
# #12 122.5   Downloading urllib3-1.26.15-py2.py3-none-any.whl (140 kB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.9/140.9 kB 9.6 MB/s eta 0:00:00
# #12 122.5 Collecting websocket-client>=0.32.0
# #12 122.5   Downloading websocket_client-1.5.1-py3-none-any.whl (55 kB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.9/55.9 kB 5.4 MB/s eta 0:00:00
# #12 122.5 Collecting itsdangerous>=2.0
# #12 122.5   Downloading itsdangerous-2.1.2-py3-none-any.whl (15 kB)
# #12 122.5 Collecting Werkzeug>=2.2.2
# #12 122.5   Downloading Werkzeug-2.2.3-py3-none-any.whl (233 kB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.6/233.6 kB 10.6 MB/s eta 0:00:00
# #12 122.5 Collecting gitdb<5,>=4.0.1
# #12 122.5   Downloading gitdb-4.0.10-py3-none-any.whl (62 kB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 9.1 MB/s eta 0:00:00
# #12 122.5 Requirement already satisfied: setuptools>=3.0 in ./.conda/envs/mlflow_env/lib/python3.10/site-packages (from gunicorn<21->mlflow<3,>=2.1->-r /home/gustavo/condaenv.ovf906j9.requirements.txt (line 1)) (67.6.1)
# #12 122.5 Collecting zipp>=0.5
# #12 122.5   Downloading zipp-3.15.0-py3-none-any.whl (6.8 kB)
# #12 122.5 Collecting MarkupSafe>=2.0
# #12 122.5   Downloading MarkupSafe-2.1.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
# #12 122.5 Collecting pillow>=6.2.0
# #12 122.5   Downloading Pillow-9.5.0-cp310-cp310-manylinux_2_28_x86_64.whl (3.4 MB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 12.3 MB/s eta 0:00:00
# #12 122.5 Collecting pyparsing>=2.3.1
# #12 122.5   Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.3/98.3 kB 10.4 MB/s eta 0:00:00
# #12 122.5 Collecting fonttools>=4.22.0
# #12 122.5   Downloading fonttools-4.39.3-py3-none-any.whl (1.0 MB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 12.6 MB/s eta 0:00:00
# #12 122.5 Collecting contourpy>=1.0.1
# #12 122.5   Downloading contourpy-1.0.7-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (300 kB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 300.3/300.3 kB 11.3 MB/s eta 0:00:00
# #12 122.5 Collecting cycler>=0.10
# #12 122.5   Downloading cycler-0.11.0-py3-none-any.whl (6.4 kB)
# #12 122.5 Collecting python-dateutil>=2.7
# #12 122.5   Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 10.7 MB/s eta 0:00:00
# #12 122.5 Collecting kiwisolver>=1.0.1
# #12 122.5   Downloading kiwisolver-1.4.4-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 10.1 MB/s eta 0:00:00
# #12 122.5 Collecting idna<4,>=2.5
# #12 122.5   Downloading idna-3.4-py3-none-any.whl (61 kB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 987.9 kB/s eta 0:00:00
# #12 122.5 Collecting charset-normalizer<4,>=2
# #12 122.5   Downloading charset_normalizer-3.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (199 kB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.3/199.3 kB 9.7 MB/s eta 0:00:00
# #12 122.5 Collecting certifi>=2017.4.17
# #12 122.5   Downloading certifi-2022.12.7-py3-none-any.whl (155 kB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.3/155.3 kB 8.5 MB/s eta 0:00:00
# #12 122.5 Collecting joblib>=1.1.1
# #12 122.5   Downloading joblib-1.2.0-py3-none-any.whl (297 kB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.0/298.0 kB 10.5 MB/s eta 0:00:00
# #12 122.5 Collecting threadpoolctl>=2.0.0
# #12 122.5   Downloading threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
# #12 122.5 Collecting slicer==0.0.7
# #12 122.5   Downloading slicer-0.0.7-py3-none-any.whl (14 kB)
# #12 122.5 Collecting tqdm>4.25.0
# #12 122.5   Downloading tqdm-4.65.0-py3-none-any.whl (77 kB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.1/77.1 kB 6.4 MB/s eta 0:00:00
# #12 122.5 Collecting numba
# #12 122.5   Downloading numba-0.56.4-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.5 MB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 11.7 MB/s eta 0:00:00
# #12 122.5 Collecting greenlet!=0.4.17
# #12 122.5   Downloading greenlet-2.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (613 kB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 613.7/613.7 kB 10.9 MB/s eta 0:00:00
# #12 122.5 Collecting smmap<6,>=3.0.1
# #12 122.5   Downloading smmap-5.0.0-py3-none-any.whl (24 kB)
# #12 122.5 Collecting numpy<2
# #12 122.5   Downloading numpy-1.23.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 12.0 MB/s eta 0:00:00
# #12 122.5 Collecting llvmlite<0.40,>=0.39.0dev0
# #12 122.5   Downloading llvmlite-0.39.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.6 MB)
# #12 122.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.6/34.6 MB 11.7 MB/s eta 0:00:00
# #12 122.5 Building wheels for collected packages: databricks-cli
# #12 122.5   Building wheel for databricks-cli (setup.py): started
# #12 122.5   Building wheel for databricks-cli (setup.py): finished with status 'done'
# #12 122.5   Created wheel for databricks-cli: filename=databricks_cli-0.17.6-py3-none-any.whl size=143221 sha256=d25d19a41efda1134c2acdc9233deaf9156c761314c7dd79f7b829dee5bb515d
# #12 122.5   Stored in directory: /home/gustavo/.cache/pip/wheels/a1/e6/15/14de2ae3f8fc0a3a648b13afc9e900801b4cfdcdd92edfa982
# #12 122.5 Successfully built databricks-cli
# #12 122.5 Installing collected packages: pytz, zipp, websocket-client, urllib3, typing-extensions, tqdm, threadpoolctl, tabulate, sqlparse, smmap, slicer, six, pyyaml, pyparsing, pymysql, pyjwt, protobuf, pillow, packaging, oauthlib, numpy, MarkupSafe, markdown, llvmlite, kiwisolver, joblib, itsdangerous, idna, gunicorn, greenlet, fonttools, entrypoints, cycler, cloudpickle, click, charset-normalizer, certifi, Werkzeug, sqlalchemy, scipy, requests, querystring-parser, python-dateutil, pyarrow, numba, Mako, Jinja2, importlib-metadata, gitdb, contourpy, scikit-learn, pandas, matplotlib, gitpython, Flask, docker, databricks-cli, alembic, shap, mlflow
# #12 122.5 Successfully installed Flask-2.2.3 Jinja2-3.1.2 Mako-1.2.4 MarkupSafe-2.1.2 Werkzeug-2.2.3 alembic-1.10.2 certifi-2022.12.7 charset-normalizer-3.1.0 click-8.1.3 cloudpickle-2.2.1 contourpy-1.0.7 cycler-0.11.0 databricks-cli-0.17.6 docker-6.0.1 entrypoints-0.4 fonttools-4.39.3 gitdb-4.0.10 gitpython-3.1.31 greenlet-2.0.2 gunicorn-20.1.0 idna-3.4 importlib-metadata-6.1.0 itsdangerous-2.1.2 joblib-1.2.0 kiwisolver-1.4.4 llvmlite-0.39.1 markdown-3.4.3 matplotlib-3.7.1 mlflow-2.2.2 numba-0.56.4 numpy-1.23.5 oauthlib-3.2.2 packaging-23.0 pandas-1.5.3 pillow-9.5.0 protobuf-4.22.1 pyarrow-11.0.0 pyjwt-2.6.0 pymysql-1.0.3 pyparsing-3.0.9 python-dateutil-2.8.2 pytz-2022.7.1 pyyaml-6.0 querystring-parser-1.2.4 requests-2.28.2 scikit-learn-1.2.2 scipy-1.10.1 shap-0.41.0 six-1.16.0 slicer-0.0.7 smmap-5.0.0 sqlalchemy-2.0.8 sqlparse-0.4.3 tabulate-0.9.0 threadpoolctl-3.1.0 tqdm-4.65.0 typing-extensions-4.5.0 urllib3-1.26.15 websocket-client-1.5.1 zipp-3.15.0
# #12 122.5
# #12 122.5 done
# #12 122.5 #
# #12 122.5 # To activate this environment, use
# #12 122.5 #
# #12 122.5 #     $ conda activate mlflow_env
# #12 122.5 #
# #12 122.5 # To deactivate an active environment, use
# #12 122.5 #
# #12 122.5 #     $ conda deactivate
# #12 122.5
# #12 DONE 127.7s

# #13 exporting to image
# #13 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
# #13 exporting layers
# #13 exporting layers 9.4s done
# #13 writing image sha256:1fe7c834ae4e8709d6114d5efb5f0ba78bc997b3a2d4a5c1592ceca17f9a62b1 done
# #13 naming to docker.io/library/mlflow_tracker_conda done
# #13 DONE 9.4s