# Good practice: Use official base images
#
FROM python:3.10-slim

# Good practice: upgrade distro packages (with last security patches).
#
RUN apt-get update && apt-get -y upgrade \
    && pip install --upgrade pip \
    && pip --version \
    && apt-get install -y procps \
    && rm -rf /var/lib/apt/lists/*

# Good practice: don't run things in containers as root.
#
RUN groupadd mlflow && useradd --create-home -g mlflow gustavo
ENV PATH /home/gustavo/.local/bin:${PATH}

# Good practice: install the app under the appuser home folder:
#
WORKDIR /home/gustavo/mlflow/

# Copy the code to run when container is started
#
COPY ./entrypoint-pip-dev.sh .
RUN chown gustavo ./entrypoint-pip-dev.sh \
    && chmod u+x ./entrypoint-pip-dev.sh

# From now on, this process is owned by gustavo
#
USER gustavo

# Install mlflow dependencies:
#
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Expose mlflow ports
#
EXPOSE 5000

# Launch the mlflow server
#
ENTRYPOINT ["/bin/bash", "./entrypoint-pip-dev.sh"]


# ======================================================================================================================================
# VERBOSE Image build:
# ======================================================================================================================================

# Build the image with:

# $ docker build -f Dockerfile-as-gustavo --progress plain --no-cache -t mlflow_tracker_slim_as_gustavo .

# Logged info:

# #1 [internal] load build definition from Dockerfile-as-gustavo
# #1 sha256:77847bb826f2384100eb1dd86fa7b6ecaab4e43e6072134f48ae58c7bde59179
# #1 transferring dockerfile: 50B done
# #1 DONE 0.0s
#
# #2 [internal] load .dockerignore
# #2 sha256:8642badceaaf1f05e2afb427ad657e994fe07aa1b6e46a89f3d39b5c2fa36f4a
# #2 transferring context: 35B done
# #2 DONE 0.0s
#
# #3 [internal] load metadata for docker.io/library/python:3.10-slim
# #3 sha256:b8cce7183299ea8471dad4044ce489ad9730ef208466a01382bd3a85a0492215
# #3 DONE 0.5s
#
# #4 [1/7] FROM docker.io/library/python:3.10-slim@sha256:7b0a5cefbcdd085faa21533c21549e55a7e66f5aed40f8d1f4de13a017e352cd
# #4 sha256:3cf59a99c4595deb0a6ac22ffe47f994a753ae4eb206482ee918e1e89f008545
# #4 CACHED
#
# #9 [internal] load build context
# #9 sha256:054c816e7701972a2cf37acf245c951735bfa9cf6f39fd097dd46ac48184b9e6
# #9 transferring context: 37B done
# #9 DONE 0.0s
#
# #5 [2/7] RUN apt-get update && apt-get -y upgrade     && pip install --upgrade pip     && pip --version
# #5 sha256:ee326e143ec81e4f7025634419c33dcc99cdf12628189df109674795020eb0d7
# #5 0.456 Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
# #5 0.493 Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
# #5 0.513 Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
# #5 0.558 Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8183 kB]
# #5 1.280 Get:5 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [236 kB]
# #5 1.300 Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [14.6 kB]
# #5 2.119 Fetched 8642 kB in 2s (5102 kB/s)
# #5 2.119 Reading package lists...
# #5 2.559 Reading package lists...
# #5 2.939 Building dependency tree...
# #5 3.043 Reading state information...
# #5 3.074 Calculating upgrade...
# #5 3.256 The following packages will be upgraded:
# #5 3.256   tzdata
# #5 3.289 1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
# #5 3.289 Need to get 286 kB of archives.
# #5 3.289 After this operation, 20.5 kB of additional disk space will be used.
# #5 3.289 Get:1 http://deb.debian.org/debian bullseye-updates/main amd64 tzdata all 2021a-1+deb11u9 [286 kB]
# #5 3.444 debconf: delaying package configuration, since apt-utils is not installed
# #5 3.472 Fetched 286 kB in 0s (3898 kB/s)
# (Reading database ... 7031 files and directories currently installed.)
# #5 3.530 Preparing to unpack .../tzdata_2021a-1+deb11u9_all.deb ...
# #5 3.558 Unpacking tzdata (2021a-1+deb11u9) over (2021a-1+deb11u8) ...
# #5 10.21 Setting up tzdata (2021a-1+deb11u9) ...
# #5 10.28 debconf: unable to initialize frontend: Dialog
# #5 10.28 debconf: (TERM is not set, so the dialog frontend is not usable.)
# #5 10.28 debconf: falling back to frontend: Readline
# #5 10.28 debconf: unable to initialize frontend: Readline
# #5 10.28 debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.32.1 /usr/local/share/perl/5.32.1 /usr/lib/x86_64-linux-gnu/perl5/5.32 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.32 /usr/share/perl/5.32 /usr/local/lib/site_perl) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
# #5 10.28 debconf: falling back to frontend: Teletype
# #5 10.31
# #5 10.31 Current default time zone: 'Etc/UTC'
# #5 10.31 Local time is now:      Sat Apr  1 10:02:31 UTC 2023.
# #5 10.31 Universal Time is now:  Sat Apr  1 10:02:31 UTC 2023.
# #5 10.31 Run 'dpkg-reconfigure tzdata' if you wish to change it.
# #5 10.31
# #5 11.40 Requirement already satisfied: pip in /usr/local/lib/python3.10/site-packages (22.3.1)
# #5 11.56 Collecting pip
# #5 11.61   Downloading pip-23.0.1-py3-none-any.whl (2.1 MB)
# #5 11.85      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 8.7 MB/s eta 0:00:00
# #5 11.90 Installing collected packages: pip
# #5 11.90   Attempting uninstall: pip
# #5 11.90     Found existing installation: pip 22.3.1
# #5 11.96     Uninstalling pip-22.3.1:
# #5 12.09       Successfully uninstalled pip-22.3.1
# #5 12.88 Successfully installed pip-23.0.1
# #5 12.88 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
# #5 13.31 pip 23.0.1 from /usr/local/lib/python3.10/site-packages/pip (python 3.10)
# #5 DONE 13.7s
#
# #6 [3/7] RUN apt-get update && apt-get install -y procps     && rm -rf /var/lib/apt/lists/*
# #6 sha256:f85b9777f5c79b62f73815a47d1ffc804a11dbcae588afc83ba4c32618e71526
# #6 0.659 Hit:1 http://deb.debian.org/debian bullseye InRelease
# #6 0.659 Hit:2 http://deb.debian.org/debian-security bullseye-security InRelease
# #6 0.662 Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
# #6 0.855 Reading package lists...
# #6 1.155 Reading package lists...
# #6 1.464 Building dependency tree...
# #6 1.539 Reading state information...
# #6 1.616 The following additional packages will be installed:
# #6 1.616   libgpm2 libncurses6 libprocps8 psmisc
# #6 1.617 Suggested packages:
# #6 1.617   gpm
# #6 1.648 The following NEW packages will be installed:
# #6 1.649   libgpm2 libncurses6 libprocps8 procps psmisc
# #6 1.693 0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
# #6 1.693 Need to get 902 kB of archives.
# #6 1.693 After this operation, 3044 kB of additional disk space will be used.
# #6 1.693 Get:1 http://deb.debian.org/debian bullseye/main amd64 libncurses6 amd64 6.2+20201114-2 [102 kB]
# #6 1.719 Get:2 http://deb.debian.org/debian bullseye/main amd64 libprocps8 amd64 2:3.3.17-5 [63.9 kB]
# #6 1.733 Get:3 http://deb.debian.org/debian bullseye/main amd64 procps amd64 2:3.3.17-5 [502 kB]
# #6 1.775 Get:4 http://deb.debian.org/debian bullseye/main amd64 libgpm2 amd64 1.20.7-8 [35.6 kB]
# #6 1.777 Get:5 http://deb.debian.org/debian bullseye/main amd64 psmisc amd64 23.4-2 [198 kB]
# #6 1.874 debconf: delaying package configuration, since apt-utils is not installed
# #6 1.904 Fetched 902 kB in 0s (6397 kB/s)
# #6 1.949 Selecting previously unselected package libncurses6:amd64.
# (Reading database ... 7034 files and directories currently installed.)
# #6 1.953 Preparing to unpack .../libncurses6_6.2+20201114-2_amd64.deb ...
# #6 1.971 Unpacking libncurses6:amd64 (6.2+20201114-2) ...
# #6 2.049 Selecting previously unselected package libprocps8:amd64.
# #6 2.050 Preparing to unpack .../libprocps8_2%3a3.3.17-5_amd64.deb ...
# #6 2.061 Unpacking libprocps8:amd64 (2:3.3.17-5) ...
# #6 2.159 Selecting previously unselected package procps.
# #6 2.160 Preparing to unpack .../procps_2%3a3.3.17-5_amd64.deb ...
# #6 2.175 Unpacking procps (2:3.3.17-5) ...
# #6 2.299 Selecting previously unselected package libgpm2:amd64.
# #6 2.300 Preparing to unpack .../libgpm2_1.20.7-8_amd64.deb ...
# #6 2.311 Unpacking libgpm2:amd64 (1.20.7-8) ...
# #6 2.381 Selecting previously unselected package psmisc.
# #6 2.381 Preparing to unpack .../psmisc_23.4-2_amd64.deb ...
# #6 2.391 Unpacking psmisc (23.4-2) ...
# #6 2.472 Setting up libgpm2:amd64 (1.20.7-8) ...
# #6 2.501 Setting up psmisc (23.4-2) ...
# #6 2.531 Setting up libncurses6:amd64 (6.2+20201114-2) ...
# #6 2.565 Setting up libprocps8:amd64 (2:3.3.17-5) ...
# #6 2.596 Setting up procps (2:3.3.17-5) ...
# #6 2.676 Processing triggers for libc-bin (2.31-13+deb11u5) ...
# #6 DONE 2.8s
#
# #7 [4/7] RUN groupadd mlflow && useradd --create-home -g mlflow gustavo
# #7 sha256:8698a56259df1db0d61378b6feead245bb3bc9119815a39d7d19a82dbfcf179d
# #7 DONE 0.6s
#
# #8 [5/7] WORKDIR /home/gustavo/mlflow/
# #8 sha256:87742f0b1fde1e4ea0382010bded90deb98a08ce1d5f279c0fc790c3fb002f23
# #8 DONE 0.1s
#
# #10 [6/7] COPY requirements.txt .
# #10 sha256:274e08e902e5a85bad8dfc5649c04e7b2511e3a1d3906a5835a27679a88eb5bf
# #10 DONE 0.1s
#
# #11 [7/7] RUN pip install --no-cache-dir -r requirements.txt
# #11 sha256:b4f1aed8b494f132aa3567cf986bdbed5b4c41ebc5eeb602f7f6c27d5a6eab9b
# #11 0.704 Defaulting to user installation because normal site-packages is not writeable
# #11 0.886 Collecting mlflow==2.2.1
# #11 0.960   Downloading mlflow-2.2.1-py3-none-any.whl (17.6 MB)
# #11 2.347      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.6/17.6 MB 12.8 MB/s eta 0:00:00
# #11 2.388 Collecting pymysql
# #11 2.401   Downloading PyMySQL-1.0.3-py3-none-any.whl (43 kB)
# #11 2.405      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 18.3 MB/s eta 0:00:00
# #11 2.596 Collecting scipy<2
# #11 2.609   Downloading scipy-1.10.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.4 MB)
# #11 5.235      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.4/34.4 MB 13.2 MB/s eta 0:00:00
# #11 5.444 Collecting pandas<3
# #11 5.455   Downloading pandas-1.5.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.1 MB)
# #11 6.435      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 12.3 MB/s eta 0:00:00
# #11 6.487 Collecting gunicorn<21
# #11 6.496   Downloading gunicorn-20.1.0-py3-none-any.whl (79 kB)
# #11 6.506      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 14.7 MB/s eta 0:00:00
# #11 6.570 Collecting pyyaml<7,>=5.1
# #11 6.585   Downloading PyYAML-6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (682 kB)
# #11 6.640      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 682.2/682.2 kB 12.7 MB/s eta 0:00:00
# #11 6.774 Collecting scikit-learn<2
# #11 6.786   Downloading scikit_learn-1.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.6 MB)
# #11 7.559      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 12.5 MB/s eta 0:00:00
# #11 7.597 Collecting cloudpickle<3
# #11 7.615   Downloading cloudpickle-2.2.1-py3-none-any.whl (25 kB)
# #11 7.660 Collecting Flask<3
# #11 7.670   Downloading Flask-2.2.3-py3-none-any.whl (101 kB)
# #11 7.679      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.8/101.8 kB 14.7 MB/s eta 0:00:00
# #11 7.701 Collecting entrypoints<1
# #11 7.711   Downloading entrypoints-0.4-py3-none-any.whl (5.3 kB)
# #11 7.742 Collecting markdown<4,>=3.3
# #11 7.769   Downloading Markdown-3.4.3-py3-none-any.whl (93 kB)
# #11 7.777      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.9/93.9 kB 16.5 MB/s eta 0:00:00
# #11 7.810 Collecting click<9,>=7.0
# #11 7.822   Downloading click-8.1.3-py3-none-any.whl (96 kB)
# #11 7.831      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 kB 14.4 MB/s eta 0:00:00
# #11 7.871 Collecting shap<1,>=0.40
# #11 7.894   Downloading shap-0.41.0-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (572 kB)
# #11 7.940      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 572.6/572.6 kB 12.9 MB/s eta 0:00:00
# #11 7.974 Collecting packaging<24
# #11 7.986   Downloading packaging-23.0-py3-none-any.whl (42 kB)
# #11 7.990      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.7/42.7 kB 22.2 MB/s eta 0:00:00
# #11 8.033 Collecting gitpython<4,>=2.1.0
# #11 8.043   Downloading GitPython-3.1.31-py3-none-any.whl (184 kB)
# #11 8.057      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 184.3/184.3 kB 16.1 MB/s eta 0:00:00
# #11 8.071 Collecting querystring-parser<2
# #11 8.080   Downloading querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
# #11 8.123 Collecting requests<3,>=2.17.3
# #11 8.139   Downloading requests-2.28.2-py3-none-any.whl (62 kB)
# #11 8.148      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 8.7 MB/s eta 0:00:00
# #11 8.519 Collecting sqlalchemy<3,>=1.4.0
# #11 8.549   Downloading SQLAlchemy-2.0.8-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.7 MB)
# #11 8.761      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 13.0 MB/s eta 0:00:00
# #11 8.794 Collecting databricks-cli<1,>=0.8.7
# #11 8.807   Downloading databricks-cli-0.17.6.tar.gz (82 kB)
# #11 8.813      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.7/82.7 kB 19.1 MB/s eta 0:00:00
# #11 8.831   Preparing metadata (setup.py): started
# #11 9.182   Preparing metadata (setup.py): finished with status 'done'
# #11 9.244 Collecting pytz<2023
# #11 9.258   Downloading pytz-2022.7.1-py2.py3-none-any.whl (499 kB)
# #11 9.304      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 499.4/499.4 kB 11.3 MB/s eta 0:00:00
# #11 9.414 Collecting pyarrow<12,>=4.0.0
# #11 9.427   Downloading pyarrow-11.0.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.9 MB)
# #11 12.13      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.9/34.9 MB 13.2 MB/s eta 0:00:00
# #11 12.23 Collecting importlib-metadata!=4.7.0,<7,>=3.7.0
# #11 12.24   Downloading importlib_metadata-6.1.0-py3-none-any.whl (21 kB)
# #11 12.43 Collecting matplotlib<4
# #11 12.44   Downloading matplotlib-3.7.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.6 MB)
# #11 13.32      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 13.3 MB/s eta 0:00:00
# #11 13.58 Collecting numpy<2
# #11 13.59   Downloading numpy-1.24.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
# #11 14.90      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 13.4 MB/s eta 0:00:00
# #11 14.95 Collecting Jinja2<4,>=2.11
# #11 14.96   Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
# #11 14.97      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 13.3 MB/s eta 0:00:00
# #11 15.00 Collecting sqlparse<1,>=0.4.0
# #11 15.01   Downloading sqlparse-0.4.3-py3-none-any.whl (42 kB)
# #11 15.01      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.8/42.8 kB 37.0 MB/s eta 0:00:00
# #11 15.05 Collecting docker<7,>=4.0.0
# #11 15.06   Downloading docker-6.0.1-py3-none-any.whl (147 kB)
# #11 15.07      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.5/147.5 kB 15.0 MB/s eta 0:00:00
# #11 15.30 Collecting protobuf<5,>=3.12.0
# #11 15.31   Downloading protobuf-4.22.1-cp37-abi3-manylinux2014_x86_64.whl (302 kB)
# #11 15.34      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.4/302.4 kB 13.0 MB/s eta 0:00:00
# #11 15.41 Collecting alembic<2
# #11 15.42   Downloading alembic-1.10.2-py3-none-any.whl (212 kB)
# #11 15.44      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.2/212.2 kB 12.1 MB/s eta 0:00:00
# #11 15.47 Collecting typing-extensions>=4
# #11 15.48   Downloading typing_extensions-4.5.0-py3-none-any.whl (27 kB)
# #11 15.50 Collecting Mako
# #11 15.51   Downloading Mako-1.2.4-py3-none-any.whl (78 kB)
# #11 15.52      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.7/78.7 kB 17.1 MB/s eta 0:00:00
# #11 15.57 Collecting pyjwt>=1.7.0
# #11 15.59   Downloading PyJWT-2.6.0-py3-none-any.whl (20 kB)
# #11 15.62 Collecting oauthlib>=3.1.0
# #11 15.64   Downloading oauthlib-3.2.2-py3-none-any.whl (151 kB)
# #11 15.65      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 151.7/151.7 kB 14.6 MB/s eta 0:00:00
# #11 15.67 Collecting tabulate>=0.7.7
# #11 15.68   Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
# #11 15.70 Collecting six>=1.10.0
# #11 15.71   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
# #11 15.77 Collecting urllib3>=1.26.0
# #11 15.79   Downloading urllib3-1.26.15-py2.py3-none-any.whl (140 kB)
# #11 15.81      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.9/140.9 kB 9.9 MB/s eta 0:00:00
# #11 15.85 Collecting websocket-client>=0.32.0
# #11 15.86   Downloading websocket_client-1.5.1-py3-none-any.whl (55 kB)
# #11 15.87      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.9/55.9 kB 30.1 MB/s eta 0:00:00
# #11 15.91 Collecting itsdangerous>=2.0
# #11 15.92   Downloading itsdangerous-2.1.2-py3-none-any.whl (15 kB)
# #11 15.96 Collecting Werkzeug>=2.2.2
# #11 15.97   Downloading Werkzeug-2.2.3-py3-none-any.whl (233 kB)
# #11 15.99      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.6/233.6 kB 12.8 MB/s eta 0:00:00
# #11 16.02 Collecting gitdb<5,>=4.0.1
# #11 16.04   Downloading gitdb-4.0.10-py3-none-any.whl (62 kB)
# #11 16.04      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 21.4 MB/s eta 0:00:00
# #11 16.05 Requirement already satisfied: setuptools>=3.0 in /usr/local/lib/python3.10/site-packages (from gunicorn<21->mlflow==2.2.1->-r requirements.txt (line 1)) (65.5.1)
# #11 16.10 Collecting zipp>=0.5
# #11 16.12   Downloading zipp-3.15.0-py3-none-any.whl (6.8 kB)
# #11 16.18 Collecting MarkupSafe>=2.0
# #11 16.19   Downloading MarkupSafe-2.1.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
# #11 16.23 Collecting python-dateutil>=2.7
# #11 16.25   Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
# #11 16.27      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 13.5 MB/s eta 0:00:00
# #11 16.31 Collecting pyparsing>=2.3.1
# #11 16.33   Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
# #11 16.33      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.3/98.3 kB 14.3 MB/s eta 0:00:00
# #11 16.40 Collecting kiwisolver>=1.0.1
# #11 16.42   Downloading kiwisolver-1.4.4-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
# #11 16.55      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 12.6 MB/s eta 0:00:00
# #11 16.62 Collecting fonttools>=4.22.0
# #11 16.63   Downloading fonttools-4.39.3-py3-none-any.whl (1.0 MB)
# #11 16.71      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 12.7 MB/s eta 0:00:00
# #11 16.98 Collecting pillow>=6.2.0
# #11 16.99   Downloading Pillow-9.5.0-cp310-cp310-manylinux_2_28_x86_64.whl (3.4 MB)
# #11 17.28      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 11.8 MB/s eta 0:00:00
# #11 17.30 Collecting cycler>=0.10
# #11 17.31   Downloading cycler-0.11.0-py3-none-any.whl (6.4 kB)
# #11 17.40 Collecting contourpy>=1.0.1
# #11 17.41   Downloading contourpy-1.0.7-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (300 kB)
# #11 17.44      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 300.3/300.3 kB 13.7 MB/s eta 0:00:00
# #11 17.61 Collecting charset-normalizer<4,>=2
# #11 17.62   Downloading charset_normalizer-3.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (199 kB)
# #11 17.64      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.3/199.3 kB 12.4 MB/s eta 0:00:00
# #11 17.66 Collecting certifi>=2017.4.17
# #11 17.68   Downloading certifi-2022.12.7-py3-none-any.whl (155 kB)
# #11 17.69      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.3/155.3 kB 13.8 MB/s eta 0:00:00
# #11 17.72 Collecting idna<4,>=2.5
# #11 17.74   Downloading idna-3.4-py3-none-any.whl (61 kB)
# #11 17.74      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 19.1 MB/s eta 0:00:00
# #11 17.79 Collecting threadpoolctl>=2.0.0
# #11 17.80   Downloading threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
# #11 17.84 Collecting joblib>=1.1.1
# #11 17.85   Downloading joblib-1.2.0-py3-none-any.whl (297 kB)
# #11 17.88      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.0/298.0 kB 13.2 MB/s eta 0:00:00
# #11 17.95 Collecting slicer==0.0.7
# #11 17.96   Downloading slicer-0.0.7-py3-none-any.whl (14 kB)
# #11 18.03 Collecting tqdm>4.25.0
# #11 18.04   Downloading tqdm-4.65.0-py3-none-any.whl (77 kB)
# #11 18.05      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.1/77.1 kB 18.5 MB/s eta 0:00:00
# #11 18.20 Collecting numba
# #11 18.21   Downloading numba-0.56.4-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.5 MB)
# #11 18.48      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 12.8 MB/s eta 0:00:00
# #11 18.69 Collecting greenlet!=0.4.17
# #11 18.70   Downloading greenlet-2.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (613 kB)
# #11 18.75      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 613.7/613.7 kB 13.1 MB/s eta 0:00:00
# #11 18.85 Collecting smmap<6,>=3.0.1
# #11 18.86   Downloading smmap-5.0.0-py3-none-any.whl (24 kB)
# #11 19.05 Collecting numpy<2
# #11 19.07   Downloading numpy-1.23.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
# #11 20.38      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 13.2 MB/s eta 0:00:00
# #11 20.48 Collecting llvmlite<0.40,>=0.39.0dev0
# #11 20.49   Downloading llvmlite-0.39.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.6 MB)
# #11 23.22      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.6/34.6 MB 13.3 MB/s eta 0:00:00
# #11 23.31 Building wheels for collected packages: databricks-cli
# #11 23.31   Building wheel for databricks-cli (setup.py): started
# #11 23.81   Building wheel for databricks-cli (setup.py): finished with status 'done'
# #11 23.81   Created wheel for databricks-cli: filename=databricks_cli-0.17.6-py3-none-any.whl size=143221 sha256=9e3a0f011cd048e4cf4b2c6ecdcc29a33262182c478d5dcb6fe5cdbf097c9017
# #11 23.81   Stored in directory: /tmp/pip-ephem-wheel-cache-z3wlk7l_/wheels/7b/85/a1/37b9b24f55c1da8ea4795765de41713b8a2cccad89c866e26b
# #11 23.81 Successfully built databricks-cli
# #11 24.13 Installing collected packages: pytz, zipp, websocket-client, urllib3, typing-extensions, tqdm, threadpoolctl, tabulate, sqlparse, smmap, slicer, six, pyyaml, pyparsing, pymysql, pyjwt, protobuf, pillow, packaging, oauthlib, numpy, MarkupSafe, markdown, llvmlite, kiwisolver, joblib, itsdangerous, idna, gunicorn, greenlet, fonttools, entrypoints, cycler, cloudpickle, click, charset-normalizer, certifi, Werkzeug, sqlalchemy, scipy, requests, querystring-parser, python-dateutil, pyarrow, numba, Mako, Jinja2, importlib-metadata, gitdb, contourpy, scikit-learn, pandas, matplotlib, gitpython, Flask, docker, databricks-cli, alembic, shap, mlflow
# #11 42.86 Successfully installed Flask-2.2.3 Jinja2-3.1.2 Mako-1.2.4 MarkupSafe-2.1.2 Werkzeug-2.2.3 alembic-1.10.2 certifi-2022.12.7 charset-normalizer-3.1.0 click-8.1.3 cloudpickle-2.2.1 contourpy-1.0.7 cycler-0.11.0 databricks-cli-0.17.6 docker-6.0.1 entrypoints-0.4 fonttools-4.39.3 gitdb-4.0.10 gitpython-3.1.31 greenlet-2.0.2 gunicorn-20.1.0 idna-3.4 importlib-metadata-6.1.0 itsdangerous-2.1.2 joblib-1.2.0 kiwisolver-1.4.4 llvmlite-0.39.1 markdown-3.4.3 matplotlib-3.7.1 mlflow-2.2.1 numba-0.56.4 numpy-1.23.5 oauthlib-3.2.2 packaging-23.0 pandas-1.5.3 pillow-9.5.0 protobuf-4.22.1 pyarrow-11.0.0 pyjwt-2.6.0 pymysql-1.0.3 pyparsing-3.0.9 python-dateutil-2.8.2 pytz-2022.7.1 pyyaml-6.0 querystring-parser-1.2.4 requests-2.28.2 scikit-learn-1.2.2 scipy-1.10.1 shap-0.41.0 six-1.16.0 slicer-0.0.7 smmap-5.0.0 sqlalchemy-2.0.8 sqlparse-0.4.3 tabulate-0.9.0 threadpoolctl-3.1.0 tqdm-4.65.0 typing-extensions-4.5.0 urllib3-1.26.15 websocket-client-1.5.1 zipp-3.15.0
# #11 DONE 47.0s
#
# #12 exporting to image
# #12 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
# #12 exporting layers
# #12 exporting layers 3.6s done
# #12 writing image sha256:44bdb3cf61f6f3a11ecda4d535f3c39304b514807fb7ed199981c3265d3c3ccd done
# #12 naming to docker.io/library/mlflow_tracker_slim_as_gustavo done
# #12 DONE 3.6s